title: George Chapman
description: >-
  South African artist George Chapman's paintings and essays. View
  artworks, read about current and past exhibitions, and subscribe for
  news and updates.
baseurl: ""
url: "https://georgechapman.studio"
instagram: gn.chapman
ga_tag: G-SEL2XXVY0C
recaptcha: 6LcorKEnAAAAAGwgRU4wqG8o68EGFh789Zqg7Lsx
newsletter_url: https://buttondown.email/georgechapman
collections:
  paintings:
    output: true
  exhibitions:
    output: true
  authors:

favicon: "favicon.ico"

# Build settings
sass:
  style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings:
    [
      html,
      head,
      body,
      li,
      dt,
      dd,
      rt,
      rp,
      optgroup,
      option,
      colgroup,
      caption,
      thead,
      tbody,
      tfoot,
      tr,
      td,
      th,
    ]
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag

exclude:
  - .jekyll-cache/
