title: George Chapman
email:
description: >-
  Website of artist George Chapman. View paintings and current
  exhibitions, and sign up for news and updates.
baseurl: ""
url: "https://gnchapman.com"
instagram: gn.chapman
newsletter_url: https://buttondown.email/georgechapman
collections:
  paintings:
    output: true
  authors:

favicon: "favicon.ico"

# Build settings
# theme: minima
sass:
    style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .jekyll-cache/
