title: George Chapman
email:
description: >-
  Website of London-based artist George Chapman. View paintings and
  current exhibitions, and sign up for news and updates.
baseurl: ""
url: "https://georgechapman.studio"
instagram: gn.chapman
ga_tag: G-SEL2XXVY0C
newsletter_url: https://buttondown.email/georgechapman
collections:
  paintings:
    output: true
  authors:

favicon: "favicon.ico"

# Build settings
sass:
    style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .jekyll-cache/
